### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by nettlebay** [j4321/FeedAgregator#7]
I am back :-(
I try to install from Github file. Look at the copy of the terminal (attached file)
[install_issue.txt](https://github.com/j4321/FeedAgregator/files/2932263/install_issue.txt)

End of install: 
```
Searching for dateutil
Reading https://pypi.org/simple/dateutil/
No local packages or working download links found for dateutil
error: Could not find suitable distribution for Requirement.parse('dateutil')
```
NOTES
- dateutil  is present in my distro
- There is nothing in https://pypi.org/simple/dateutil/

**Comment by j4321** [comment]
Thanks for reporting this. I made a mistake in the name of the module which is [python-dateutil](https://pypi.org/project/python-dateutil/) instead of just dateutil.

**Comment by nettlebay** [comment]
Ok!

Le mar. 5 mars 2019 à 16:16, Juliette Monsel <notifications@github.com> a
écrit :
